server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: beans,mappings
chatglm:
  sdk:
    config:
      api-host: https://open.bigmodel.cn/
      api-key: 304a4f67c2699e6a7fe3f177f03ee904.kihba8xg1VfHlWRZ
